config/routes.rb
Rails.application.routes.draw do
  
  get 'all_users' => 'admin#all_users'

  post 'edit_user' =>'admin#edit_user'

  get 'show_user' => 'admin#show_user'

 post 'delete_line_item' => 'cart#delete_line_item'
 get 'delete_line_item' => 'cart#delete_line_item'


	get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'

  post 'add_to_cart' =>'cart#add_to_cart'

  get 'view_order' =>'cart#view_order'

  get 'checkout' => 'cart#checkout'

  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category' 

  get 'branding' => 'storefront#items_by_brand'

  post 'order_complete' => 'cart#order_complete'

  devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mike's Crazy House of Swag!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
   <!-- Begin of Navbar -->
   <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <ul class= "nav navbar-nav navbar-left" >
          <li><i class="fa fa-home fa-2x fa-pull-left navbar-brand" > 
          <span class="brand-font"><%= link_to "All Deals", root_path %></span> </i></li>
        </ul>
     
      </div>

  
      <!-- Collect the nav links, forms, and other content for toggling -->

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
        <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? && current_user.role == "admin" %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><%= link_to "Users", all_users_path %></li>
         
                <li><%= link_to 'Inventory', products_path %></li>
            </ul>
          </li> 
        <% end %>    

          <li><%= link_to "All Items", root_path %></li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @categories.each do |category| %>
                <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
              <% end %>
            </ul>
          </li>



          <!-- Brands -->
        
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @brands.each do |brand| %>
                <li><%= link_to brand, branding_path(brand: brand) %></li>
              <% end %>
                <li><%= link_to 'All', root_path %></li>
            </ul>
          </li>  
          <!-- End Brands -->   

          <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "View Cart", view_order_path %></li>
          <% if user_signed_in? %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
      
                Welcome <%= current_user.email %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% else %>
             <li><%= link_to 'Sign In', new_user_session_path %></li> 
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
  <div class="header" >
  <center><strong><h1>Mike's Crazy House of Swag!</h1></strong>
  <p>The best products for the best price!</p></center>
</div>
  <!-- End of Navbar -->
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>